
//Exception
// try catch
void main(){
  var i = [2,33,4,1,2,3,4];
try {
  print(i[33]);
  
} catch (e) {
  print("Tiana , you are trying to access an invalid index");
}
//print("Hello Tiana is here");

}
